module.exports = {
  bootstrapPrompt: require('./prompt'),
  bootstrapBanner: require('./banner'),
  fixUsrLocal: require('./usrlocal'),
  bootstrapProfile: require('./profile'),
  bootstrapProxy: require('./proxy'),
  checkForApps: require('./checkForApps'),
  bootstrapEslintConfiguration: require('./eslint'),
  bootstrapJsBeautifyConfiguration: require('./jsBeautify'),
  bootstrapGitConfiguration: require('./git'),
  bootstrapNodeAndNpm: require('./node'),
  bootstrapHomebrew: require('./homebrew'),
  bootstrapRuby: require('./ruby'),
  bootstrapMaven: require('./maven'),
  installFedtools: require('./fedtools'),
  installQuickLookPlugins: require('./quicklook'),
  fixScreensaver: require('./screensaver'),
  bootstrapAtom: require('./atom'),
  bootstrapSinopia: require('./sinopia'),
  togglePowerChimeSound: require('./powerChime')
};
